### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by kdeng00** [Ranceg/Gas-Price-Predictor#2]
Hey @Ranceg,
Since we're going to be predicting gas prices we're going to need to store data, a database will achieve this but which one do you want to go with? Since we will be using Django, the supported databases are:
* MySQL
* Microsoft SQL Server
* PostgreSQL

I haven't tried PostgreSQL before but I have experience with the other two. Let me know what you think.

**Comment by Ranceg** [comment]
I like that coding style. Keeps things organized. I think i want to use
MySQL.
