### ISSUE TITLE
Initialize Django project

### ISSUE THREAD

**Issue by kdeng00** [Ranceg/Gas-Price-Predictor#3]
Hey @Ranceg,
To start the project we need to get Django pushed into the master branch. I run Linux but that shouldn't matter, Django does not depend on a specific OS. Use an OS that makes it easy for you to develop in. I've already setup a Django project before, if you want me to initialize it I can but if you want to initialize it then you can do it. Here is a [resource](https://docs.djangoproject.com/en/2.2/topics/install/). Afterwards we can start designing, adding more issues, pick which issues to take on, and how the project will turn out.

**Comment by Ranceg** [comment]
> Alright cool. I'll review this and try to learn how to set it up. Maybe
> you can correct my mistakes when I'm done.


I dont think I've ever developed in linux specifically but I want to
attempt it just to see how it is compared to Windows.

>
>

**Comment by kdeng00** [comment]
@Ranceg, 
How do you normally develop? Usually in Windows? Did you use use Visual Studio, Eclipse, PyCharm, etc. for the IDE? Did you use a text editor like Visual Studio Code, notepad++, notepad, atom, sublime text, etc.?

I would say choose whichever works best for you or if you want to get into Linux as well then it will make things easier to develop. The terminal gives you more control over developing software and interacting with your system. That applies to Windows, Mac OS, Linux, or UNIX. If you want to try Linux I'd try Manjaro Linux or Ubuntu to start off. They come pre-installed with packages to help with development but if you ever need to install something you can do so without leaving the terminal or even using the mouse. It's not that hard either to get Linux on your PC. All you need is a spare USB (4GB is enough), download the Linux ISO, make the USB bootable with the ISO, back up any important data, boot from the USB, install the OS.

You could also dual boot, the booting from the USB will give you the option to install the OS with Windows if you still want to use Windows.

**Comment by Ranceg** [comment]
Normally for python, I use either the ide or atom in Windows. I normally
have the terminal snapped to the side opposite of atom. I actually have
Kali linux on my laptop dual booted with Windows.

>
How about you?

**Comment by kdeng00** [comment]
I keep it simple, Arch Linux (or any Linux OS would do), vim, and a rxvt-unicode terminal is all I need to develop.

Gotcha, so you already have Linux. In that case you can choose to work in either environment. It's pretty easy to setup a Django project, I think Atom as a plugin for Github. If not then you can use the git shell or Github desktop on Windows to interact with the repo. If on Linux that can be done in the terminal. I'd say pick whichever you believe would be easiest to develop with

**Comment by Ranceg** [comment]
I think i'll work on this project in the windows environment.

**Comment by kdeng00** [comment]
Hey @Ranceg,

I'll initialize the project later on tonight and create a PR (Pull Request). If you want to review anything I can do so before you merge it to the master branch of Gas-Price-Predictor.

**Comment by kdeng00** [comment]
@Ranceg,

No problem. I made a development branch so I could work on changes without affecting the master. I leave the master branch for when I fetch updates from the original master branch (yours). The branch doesn't have to be development, it could be anything.

**Comment by Ranceg** [comment]
Alright.
It appears the django structure is in place. So what should the next step
be?

**Comment by kdeng00** [comment]
Next step is to create the Django app, the Django project has already been created. The app will be a web application that contains logic, view, and models of the project. After the app has been created we have the following to move on to:
* Configure database
* Layout models (for database structures, tables, etc.)
* Laying out how the website will look (Home page, about page, etc.)
* Figure out how to collect Gas prices and store them

Good thing about this is we can start splitting the work. After the Django app has been created we can then start with the next steps listed above.

**Comment by Ranceg** [comment]
Alright. I'll work on the django app a little later today.
